data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?", stringsAsFactors=FALSE)
data$DateTime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
subset_data <- subset(data, as.Date(data$Date, "%d/%m/%Y") >= "2007-02-01" & as.Date(data$Date, "%d/%m/%Y") <= "2007-02-02")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(subset_data$DateTime, as.numeric(subset_data$Global_active_power), type="l", xlab="", ylab="Global Active Power")
plot(subset_data$DateTime, as.numeric(subset_data$Voltage), type="l", xlab="datetime", ylab="Voltage")
plot(subset_data$DateTime, subset_data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(subset_data$DateTime, subset_data$Sub_metering_2, col="red")
lines(subset_data$DateTime, subset_data$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1, bty="n")
plot(subset_data$DateTime, as.numeric(subset_data$Global_reactive_power), type="l", xlab="datetime", ylab="Global Reactive Power")
dev.off()